#!/usr/bin/env python

# This is a wrapper for the kextract C extensions that allows you to
# choose which kextract extension version to use.

import sys
import argparse
import kmaxtools.about
import kmaxtools.kextractcommon

if __name__ == '__main__':

  usage = """\
kextract [--module-version version] arg1 arg2 ...

\t--module-version version\tSpecify the version of the Kconfig parser to use.  Defaults to \"latest\".  %s.

Kmax Tools %s
""" % (kmaxtools.about.__version__, kmaxtools.kextractcommon.available_versions)

  args = sys.argv

  # remove program name
  args = args[1:]
  
  if len(args) == 0:
    sys.stderr.write(usage)
    exit(0)

  module_version = "latest"
  if args[0] == "--module-version":
    args = args[1:]
    if len(args) == 0:
      sys.stderr.write(usage)
      exit(0)
    module_version = args[0]
    args = args[1:]

  if len(args) == 0:
    sys.stderr.write(usage)
    exit(0)
    
  if module_version == "latest":
    module_version = kmaxtools.kextractcommon.latest_module

  if module_version not in kmaxtools.kextractcommon.module_versions.keys():
    sys.stderr.write("Invalid module version \"%s\".  %s.\n" % (module_version, available_versions))
    exit(1)

  kmaxtools.kextractcommon.kextract(module_version, args)
