#!/usr/bin/env python

import kconfig_extractor_v1
import kconfig_extractor_v2
import sys
import argparse

def get_srcarch(arch):
  srcarch = {
    "x86_64" : "x86",
    "i386" : "x86",
    "sparc64" : "sparc",
    "sparc" : "sparc",
    "sh64" : "sh",
    "sh" : "sh",
  }

  if arch in srcarch.keys():
    return srcarch[arch]
  else:
    return arch

if __name__ == '__main__':
  argparser = argparse.ArgumentParser()
  argparser.add_argument("arch",
                         help="The architecture to extract Kconfig for.")
  argparser.add_argument("output",
                         help="The output file to write to.")
  argparser.add_argument("kconfig_version",
                         help="v1 = old kconfig parser", action='store_true')
  args = argparser.parse_args()

#TODO: figure out python argparser library; how to add
# another command line argument "v1"

  arch = args.arch
  output = args.output
  kconfig_version = args.kconfig_version
  srcarch = get_srcarch(arch)

#if kconfig_version is not None:
##  kconfig_extractor_v1.extract_kconfig(output, "ARCH=%s" % (arch), "SRCARCH=%s" % (srcarch))
#else:
kconfig_extractor_v2.extract_kconfig(output, "ARCH=%s" % (arch), "SRCARCH=%s" % (srcarch))